spring.datasource.url: jdbc:mysql://localhost:3306/dp_blog?serverTimezone=UTC
spring.datasource.username: dpBlog
spring.datasource.password: dpBlog
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true
spring:
  jpa:
    properties:
      hibernate:
        type: TRACE
global:
  settings:
    - code: MULTIUSER_MODE
      name: Многопользовательский режим
      value: 'NO'
    - code: POST_PREMODERATIO
      name: Премодерация постов
      value: 'NO'
    - code: STATISTICS_IS_PUBLIC
      name: Показывать всем статистику блога
      value: 'YES'

blog:
  header:
    title: DevPub
    subtitle: Рассказы разработчиков
    phone: +7 9145467551
    email: alkarik@ya.ru
    copyright: Александр Карпович
    copyrightFrom: 2020

captcha.deleteAfterMin: 60

support.email: admin@hiik.ru
spring.mail.host: mail.hiik.ru
spring.mail.username: alkarik
spring.mail.password:
spring.mail.port: 25
spring.mail.protocol: smtp

upload:
  path: "src/main/resources"
  dir: "/upload"